spring.application.name=td5_spring_boo
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=raketa
spring.datasource.driver-class-name=org.postgresql.Driver